# Generated by Django 5.1.6 on 2025-02-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSummary',
            fields=[
                ('transaction_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('transaction_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_method', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('processed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('processed_t_date', models.DateField(blank=True, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'payment_summary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionSummary',
            fields=[
                ('transaction_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('payment_transaction_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_method', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('processed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('processed_transaction_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transaction_summary',
                'managed': False,
            },
        ),
    ]
