# Generated by Django 5.1.6 on 2025-03-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_paymentsummary_transactionsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=255)),
                ('audit_time', models.DateTimeField()),
                ('audit_user', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=255)),
                ('date_last_modified', models.DateTimeField()),
            ],
        ),
    ]
