# Generated by Django 5.1.6 on 2025-03-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_vendorinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorinfo',
            name='audit_time',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
