# Generated by Django 5.1.6 on 2025-03-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_vendorinfo_audit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorinfo',
            name='date_last_modified',
            field=models.DateTimeField(),
        ),
    ]
